package com.wemarklinks.factory.data.model;

import java.io.Serializable;
import java.util.Date;

public class CodeInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.id
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.code
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.created_time
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private Date created_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.assigned_time
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private Date assigned_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.prod_type
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private Integer prod_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.prod_batch
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private String prod_batch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.status
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.from_loc
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private String from_loc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.to_loc
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private String to_loc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.discovered_time
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private Date discovered_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.discovered_loc
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private String discovered_loc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.id
     *
     * @return the value of tb_code_info.id
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.id
     *
     * @param id the value for tb_code_info.id
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.code
     *
     * @return the value of tb_code_info.code
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.code
     *
     * @param code the value for tb_code_info.code
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.created_time
     *
     * @return the value of tb_code_info.created_time
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public Date getCreated_time() {
        return created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.created_time
     *
     * @param created_time the value for tb_code_info.created_time
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setCreated_time(Date created_time) {
        this.created_time = created_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.assigned_time
     *
     * @return the value of tb_code_info.assigned_time
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public Date getAssigned_time() {
        return assigned_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.assigned_time
     *
     * @param assigned_time the value for tb_code_info.assigned_time
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setAssigned_time(Date assigned_time) {
        this.assigned_time = assigned_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.prod_type
     *
     * @return the value of tb_code_info.prod_type
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public Integer getProd_type() {
        return prod_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.prod_type
     *
     * @param prod_type the value for tb_code_info.prod_type
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setProd_type(Integer prod_type) {
        this.prod_type = prod_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.prod_batch
     *
     * @return the value of tb_code_info.prod_batch
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public String getProd_batch() {
        return prod_batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.prod_batch
     *
     * @param prod_batch the value for tb_code_info.prod_batch
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setProd_batch(String prod_batch) {
        this.prod_batch = prod_batch == null ? null : prod_batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.status
     *
     * @return the value of tb_code_info.status
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.status
     *
     * @param status the value for tb_code_info.status
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.from_loc
     *
     * @return the value of tb_code_info.from_loc
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public String getFrom_loc() {
        return from_loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.from_loc
     *
     * @param from_loc the value for tb_code_info.from_loc
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setFrom_loc(String from_loc) {
        this.from_loc = from_loc == null ? null : from_loc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.to_loc
     *
     * @return the value of tb_code_info.to_loc
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public String getTo_loc() {
        return to_loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.to_loc
     *
     * @param to_loc the value for tb_code_info.to_loc
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setTo_loc(String to_loc) {
        this.to_loc = to_loc == null ? null : to_loc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.discovered_time
     *
     * @return the value of tb_code_info.discovered_time
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public Date getDiscovered_time() {
        return discovered_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.discovered_time
     *
     * @param discovered_time the value for tb_code_info.discovered_time
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setDiscovered_time(Date discovered_time) {
        this.discovered_time = discovered_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.discovered_loc
     *
     * @return the value of tb_code_info.discovered_loc
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public String getDiscovered_loc() {
        return discovered_loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.discovered_loc
     *
     * @param discovered_loc the value for tb_code_info.discovered_loc
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setDiscovered_loc(String discovered_loc) {
        this.discovered_loc = discovered_loc == null ? null : discovered_loc.trim();
    }
}