package com.wemarklinks.factory.data.model;

import java.io.Serializable;
import java.util.Date;

public class CodeInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.id
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.category
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.batch
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private String batch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.code
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.baseurl
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private String baseurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.boxcode
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private String boxcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.assigned_time
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private Date assigned_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.from_loc
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private String from_loc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.to_loc
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private String to_loc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.status
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.outdoor_time
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private Date outdoor_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.discovered_loc
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private String discovered_loc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_code_info.discovered_time
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private Date discovered_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.id
     *
     * @return the value of tb_code_info.id
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.id
     *
     * @param id the value for tb_code_info.id
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.category
     *
     * @return the value of tb_code_info.category
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.category
     *
     * @param category the value for tb_code_info.category
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.batch
     *
     * @return the value of tb_code_info.batch
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.batch
     *
     * @param batch the value for tb_code_info.batch
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.code
     *
     * @return the value of tb_code_info.code
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.code
     *
     * @param code the value for tb_code_info.code
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.baseurl
     *
     * @return the value of tb_code_info.baseurl
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public String getBaseurl() {
        return baseurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.baseurl
     *
     * @param baseurl the value for tb_code_info.baseurl
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setBaseurl(String baseurl) {
        this.baseurl = baseurl == null ? null : baseurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.boxcode
     *
     * @return the value of tb_code_info.boxcode
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public String getBoxcode() {
        return boxcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.boxcode
     *
     * @param boxcode the value for tb_code_info.boxcode
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setBoxcode(String boxcode) {
        this.boxcode = boxcode == null ? null : boxcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.assigned_time
     *
     * @return the value of tb_code_info.assigned_time
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public Date getAssigned_time() {
        return assigned_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.assigned_time
     *
     * @param assigned_time the value for tb_code_info.assigned_time
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setAssigned_time(Date assigned_time) {
        this.assigned_time = assigned_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.from_loc
     *
     * @return the value of tb_code_info.from_loc
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public String getFrom_loc() {
        return from_loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.from_loc
     *
     * @param from_loc the value for tb_code_info.from_loc
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setFrom_loc(String from_loc) {
        this.from_loc = from_loc == null ? null : from_loc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.to_loc
     *
     * @return the value of tb_code_info.to_loc
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public String getTo_loc() {
        return to_loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.to_loc
     *
     * @param to_loc the value for tb_code_info.to_loc
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setTo_loc(String to_loc) {
        this.to_loc = to_loc == null ? null : to_loc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.status
     *
     * @return the value of tb_code_info.status
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.status
     *
     * @param status the value for tb_code_info.status
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.outdoor_time
     *
     * @return the value of tb_code_info.outdoor_time
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public Date getOutdoor_time() {
        return outdoor_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.outdoor_time
     *
     * @param outdoor_time the value for tb_code_info.outdoor_time
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setOutdoor_time(Date outdoor_time) {
        this.outdoor_time = outdoor_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.discovered_loc
     *
     * @return the value of tb_code_info.discovered_loc
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public String getDiscovered_loc() {
        return discovered_loc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.discovered_loc
     *
     * @param discovered_loc the value for tb_code_info.discovered_loc
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setDiscovered_loc(String discovered_loc) {
        this.discovered_loc = discovered_loc == null ? null : discovered_loc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_code_info.discovered_time
     *
     * @return the value of tb_code_info.discovered_time
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public Date getDiscovered_time() {
        return discovered_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_code_info.discovered_time
     *
     * @param discovered_time the value for tb_code_info.discovered_time
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    public void setDiscovered_time(Date discovered_time) {
        this.discovered_time = discovered_time;
    }
}