package com.wemarklinks.factory.data.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CodeInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public CodeInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCreated_timeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreated_timeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreated_timeEqualTo(Date value) {
            addCriterion("created_time =", value, "created_time");
            return (Criteria) this;
        }

        public Criteria andCreated_timeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "created_time");
            return (Criteria) this;
        }

        public Criteria andCreated_timeGreaterThan(Date value) {
            addCriterion("created_time >", value, "created_time");
            return (Criteria) this;
        }

        public Criteria andCreated_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "created_time");
            return (Criteria) this;
        }

        public Criteria andCreated_timeLessThan(Date value) {
            addCriterion("created_time <", value, "created_time");
            return (Criteria) this;
        }

        public Criteria andCreated_timeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "created_time");
            return (Criteria) this;
        }

        public Criteria andCreated_timeIn(List<Date> values) {
            addCriterion("created_time in", values, "created_time");
            return (Criteria) this;
        }

        public Criteria andCreated_timeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "created_time");
            return (Criteria) this;
        }

        public Criteria andCreated_timeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "created_time");
            return (Criteria) this;
        }

        public Criteria andCreated_timeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "created_time");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeIsNull() {
            addCriterion("assigned_time is null");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeIsNotNull() {
            addCriterion("assigned_time is not null");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeEqualTo(Date value) {
            addCriterion("assigned_time =", value, "assigned_time");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeNotEqualTo(Date value) {
            addCriterion("assigned_time <>", value, "assigned_time");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeGreaterThan(Date value) {
            addCriterion("assigned_time >", value, "assigned_time");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("assigned_time >=", value, "assigned_time");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeLessThan(Date value) {
            addCriterion("assigned_time <", value, "assigned_time");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeLessThanOrEqualTo(Date value) {
            addCriterion("assigned_time <=", value, "assigned_time");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeIn(List<Date> values) {
            addCriterion("assigned_time in", values, "assigned_time");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeNotIn(List<Date> values) {
            addCriterion("assigned_time not in", values, "assigned_time");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeBetween(Date value1, Date value2) {
            addCriterion("assigned_time between", value1, value2, "assigned_time");
            return (Criteria) this;
        }

        public Criteria andAssigned_timeNotBetween(Date value1, Date value2) {
            addCriterion("assigned_time not between", value1, value2, "assigned_time");
            return (Criteria) this;
        }

        public Criteria andProd_typeIsNull() {
            addCriterion("prod_type is null");
            return (Criteria) this;
        }

        public Criteria andProd_typeIsNotNull() {
            addCriterion("prod_type is not null");
            return (Criteria) this;
        }

        public Criteria andProd_typeEqualTo(Integer value) {
            addCriterion("prod_type =", value, "prod_type");
            return (Criteria) this;
        }

        public Criteria andProd_typeNotEqualTo(Integer value) {
            addCriterion("prod_type <>", value, "prod_type");
            return (Criteria) this;
        }

        public Criteria andProd_typeGreaterThan(Integer value) {
            addCriterion("prod_type >", value, "prod_type");
            return (Criteria) this;
        }

        public Criteria andProd_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("prod_type >=", value, "prod_type");
            return (Criteria) this;
        }

        public Criteria andProd_typeLessThan(Integer value) {
            addCriterion("prod_type <", value, "prod_type");
            return (Criteria) this;
        }

        public Criteria andProd_typeLessThanOrEqualTo(Integer value) {
            addCriterion("prod_type <=", value, "prod_type");
            return (Criteria) this;
        }

        public Criteria andProd_typeIn(List<Integer> values) {
            addCriterion("prod_type in", values, "prod_type");
            return (Criteria) this;
        }

        public Criteria andProd_typeNotIn(List<Integer> values) {
            addCriterion("prod_type not in", values, "prod_type");
            return (Criteria) this;
        }

        public Criteria andProd_typeBetween(Integer value1, Integer value2) {
            addCriterion("prod_type between", value1, value2, "prod_type");
            return (Criteria) this;
        }

        public Criteria andProd_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("prod_type not between", value1, value2, "prod_type");
            return (Criteria) this;
        }

        public Criteria andProd_batchIsNull() {
            addCriterion("prod_batch is null");
            return (Criteria) this;
        }

        public Criteria andProd_batchIsNotNull() {
            addCriterion("prod_batch is not null");
            return (Criteria) this;
        }

        public Criteria andProd_batchEqualTo(String value) {
            addCriterion("prod_batch =", value, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchNotEqualTo(String value) {
            addCriterion("prod_batch <>", value, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchGreaterThan(String value) {
            addCriterion("prod_batch >", value, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchGreaterThanOrEqualTo(String value) {
            addCriterion("prod_batch >=", value, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchLessThan(String value) {
            addCriterion("prod_batch <", value, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchLessThanOrEqualTo(String value) {
            addCriterion("prod_batch <=", value, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchLike(String value) {
            addCriterion("prod_batch like", value, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchNotLike(String value) {
            addCriterion("prod_batch not like", value, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchIn(List<String> values) {
            addCriterion("prod_batch in", values, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchNotIn(List<String> values) {
            addCriterion("prod_batch not in", values, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchBetween(String value1, String value2) {
            addCriterion("prod_batch between", value1, value2, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andProd_batchNotBetween(String value1, String value2) {
            addCriterion("prod_batch not between", value1, value2, "prod_batch");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andFrom_locIsNull() {
            addCriterion("from_loc is null");
            return (Criteria) this;
        }

        public Criteria andFrom_locIsNotNull() {
            addCriterion("from_loc is not null");
            return (Criteria) this;
        }

        public Criteria andFrom_locEqualTo(String value) {
            addCriterion("from_loc =", value, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locNotEqualTo(String value) {
            addCriterion("from_loc <>", value, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locGreaterThan(String value) {
            addCriterion("from_loc >", value, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locGreaterThanOrEqualTo(String value) {
            addCriterion("from_loc >=", value, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locLessThan(String value) {
            addCriterion("from_loc <", value, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locLessThanOrEqualTo(String value) {
            addCriterion("from_loc <=", value, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locLike(String value) {
            addCriterion("from_loc like", value, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locNotLike(String value) {
            addCriterion("from_loc not like", value, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locIn(List<String> values) {
            addCriterion("from_loc in", values, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locNotIn(List<String> values) {
            addCriterion("from_loc not in", values, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locBetween(String value1, String value2) {
            addCriterion("from_loc between", value1, value2, "from_loc");
            return (Criteria) this;
        }

        public Criteria andFrom_locNotBetween(String value1, String value2) {
            addCriterion("from_loc not between", value1, value2, "from_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locIsNull() {
            addCriterion("to_loc is null");
            return (Criteria) this;
        }

        public Criteria andTo_locIsNotNull() {
            addCriterion("to_loc is not null");
            return (Criteria) this;
        }

        public Criteria andTo_locEqualTo(String value) {
            addCriterion("to_loc =", value, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locNotEqualTo(String value) {
            addCriterion("to_loc <>", value, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locGreaterThan(String value) {
            addCriterion("to_loc >", value, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locGreaterThanOrEqualTo(String value) {
            addCriterion("to_loc >=", value, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locLessThan(String value) {
            addCriterion("to_loc <", value, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locLessThanOrEqualTo(String value) {
            addCriterion("to_loc <=", value, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locLike(String value) {
            addCriterion("to_loc like", value, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locNotLike(String value) {
            addCriterion("to_loc not like", value, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locIn(List<String> values) {
            addCriterion("to_loc in", values, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locNotIn(List<String> values) {
            addCriterion("to_loc not in", values, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locBetween(String value1, String value2) {
            addCriterion("to_loc between", value1, value2, "to_loc");
            return (Criteria) this;
        }

        public Criteria andTo_locNotBetween(String value1, String value2) {
            addCriterion("to_loc not between", value1, value2, "to_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeIsNull() {
            addCriterion("discovered_time is null");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeIsNotNull() {
            addCriterion("discovered_time is not null");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeEqualTo(Date value) {
            addCriterion("discovered_time =", value, "discovered_time");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeNotEqualTo(Date value) {
            addCriterion("discovered_time <>", value, "discovered_time");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeGreaterThan(Date value) {
            addCriterion("discovered_time >", value, "discovered_time");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("discovered_time >=", value, "discovered_time");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeLessThan(Date value) {
            addCriterion("discovered_time <", value, "discovered_time");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeLessThanOrEqualTo(Date value) {
            addCriterion("discovered_time <=", value, "discovered_time");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeIn(List<Date> values) {
            addCriterion("discovered_time in", values, "discovered_time");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeNotIn(List<Date> values) {
            addCriterion("discovered_time not in", values, "discovered_time");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeBetween(Date value1, Date value2) {
            addCriterion("discovered_time between", value1, value2, "discovered_time");
            return (Criteria) this;
        }

        public Criteria andDiscovered_timeNotBetween(Date value1, Date value2) {
            addCriterion("discovered_time not between", value1, value2, "discovered_time");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locIsNull() {
            addCriterion("discovered_loc is null");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locIsNotNull() {
            addCriterion("discovered_loc is not null");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locEqualTo(String value) {
            addCriterion("discovered_loc =", value, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locNotEqualTo(String value) {
            addCriterion("discovered_loc <>", value, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locGreaterThan(String value) {
            addCriterion("discovered_loc >", value, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locGreaterThanOrEqualTo(String value) {
            addCriterion("discovered_loc >=", value, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locLessThan(String value) {
            addCriterion("discovered_loc <", value, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locLessThanOrEqualTo(String value) {
            addCriterion("discovered_loc <=", value, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locLike(String value) {
            addCriterion("discovered_loc like", value, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locNotLike(String value) {
            addCriterion("discovered_loc not like", value, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locIn(List<String> values) {
            addCriterion("discovered_loc in", values, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locNotIn(List<String> values) {
            addCriterion("discovered_loc not in", values, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locBetween(String value1, String value2) {
            addCriterion("discovered_loc between", value1, value2, "discovered_loc");
            return (Criteria) this;
        }

        public Criteria andDiscovered_locNotBetween(String value1, String value2) {
            addCriterion("discovered_loc not between", value1, value2, "discovered_loc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_code_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 29 00:35:17 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_code_info
     *
     * @mbggenerated Wed Jun 29 00:35:17 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}