package com.wemarklinks.factory.data.dao;

import com.wemarklinks.factory.data.model.CodeInfo;
import com.wemarklinks.factory.data.model.CodeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CodeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    int countByExample(CodeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    int deleteByExample(CodeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    int insert(CodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    int insertSelective(CodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    List<CodeInfo> selectByExampleWithRowbounds(CodeInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    List<CodeInfo> selectByExample(CodeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    CodeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") CodeInfo record, @Param("example") CodeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    int updateByExample(@Param("record") CodeInfo record, @Param("example") CodeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    int updateByPrimaryKeySelective(CodeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_code_info
     *
     * @mbggenerated Sat Jul 16 00:24:14 CST 2016
     */
    int updateByPrimaryKey(CodeInfo record);
}